// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// interface.js
export const SET_MENU_COLLAPSED = 'SET_MENU_COLLAPSED'
export const SET_PRIORITY_COPY_TYPE_CODE_STATE = 'SET_PRIORITY_COPY_TYPE_CODE_STATE'
export const SET_HASH_GROUPS = 'SET_HASH_GROUPS'
export const SET_NAV_HASHES = 'SET_NAV_HASHES'
export const SET_FILTER_PLUGINS = 'SET_FILTER_PLUGINS'
export const SET_CARDS_OR_LIST_PLUGINS = 'SET_CARDS_OR_LIST_PLUGINS'
export const SET_CUR_LIST_CATEGORY_PLUGINS = 'SET_CUR_LIST_CATEGORY_PLUGINS'

// menu.js
export const SET_MENU_ADMIN_MATERIALS = 'SET_MENU_ADMIN_MATERIALS'
export const SET_MENU_CLIENT = 'SET_MENU_CLIENT'
export const SET_ITEMS_RELATED_DATA = 'SET_ITEMS_RELATED_DATA'

// db.js
export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES'
export const REFRESH_CATEGORIES_PUBLIC = 'REFRESH_CATEGORIES_PUBLIC'
export const REFRESH_CATEGORIES_PUBLIC_TREE = 'REFRESH_CATEGORIES_PUBLIC_TREE'
export const LOAD_TAX_PUBLIC_PPMM = 'LOAD_TAX_PUBLIC_PPMM'

// content-widgets.js
export const SET_SELECT_POSITION = 'SET_SELECT_POSITION'
export const SET_WIDGETS_TYPES = 'SET_WIDGETS_TYPES'
export const SET_SELECT_COPY_CODE = 'SET_SELECT_COPY_CODE'