// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// interface.js
export const SET_MENU_COLLAPSED = 'SET_MENU_COLLAPSED'
export const SET_PLUGINS_SIDEBAR_MEGAMENU_STATE = 'SET_PLUGINS_SIDEBAR_MEGAMENU_STATE'
export const SET_PRIORITY_COPY_TYPE_CODE_STATE = 'SET_PRIORITY_COPY_TYPE_CODE_STATE'

// menu.js
export const SET_MENU_ADMIN_MATERIALS = 'SET_MENU_ADMIN_MATERIALS'
export const SET_MENU_CLIENT = 'SET_MENU_CLIENT'

// db.js
export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES'

// content-widgets.js
export const SET_SELECT_POSITION = 'SET_SELECT_POSITION'
export const SET_WIDGETS_TYPES = 'SET_WIDGETS_TYPES'
export const SET_SELECT_COPY_CODE = 'SET_SELECT_COPY_CODE'